### PR TITLE
fix: use moveDirectory instead of os.Rename

### LINKED ISSUE #1: `lets init static` failed when moving the uncompressed files
When I follow the documentation: https://docs.let.sh/, and try to deploy the static site, this issue occurs to me.

image
image

We should use another way to move files across different devices.

Related codes:
https://github.com/let-sh/cli/blob/87ce54b0344e297723e971adf5a1a75c35504a5f/cmd/init.go#L81-L87

I am very pleased to contribute to fix this issue, fell free to assign this issue on me

### PR DESCRIPTION
**Pull request by STRRL**
os.Rename could not move file/dir across different devices

close #1

Signed-off-by: STRRL <im@strrl.dev>

### CODE REVIEW

**Review by 5kbpers — APPROVED** [review]
LGTM, thanks!

**Comment by fredliang44** [comment]
Thanks for your PR, have you tested in your machine?

**Comment by fredliang44** [comment]
And there is a lot of `os.Rename` operation inside cli. We may also consider migrate them in to the new method. @5kbpers

**Comment by STRRL** [comment]
> Thanks for your PR, have you tested in your machine?

yes! It works on my local machine.

**Comment by fredliang44** [comment]
@STRRL released, you can use `lets upgrade` to upgrade cli to latest v0.2.43

**Comment by STRRL** [comment]
It seems `lets upgrade` also used `os.Rename`, so I failed to upgrade. 🤣🤣🤣

image


I would try to upgrade `lets` manaully.

**Comment by fredliang44** [comment]
f**k, is seems its urgent to change all of the `os.Rename`

**Comment by fredliang44** [comment]
@STRRL fixed in v0.2.44,you can use install script again to force upgrade your cli version

**Pull request merged**
